POST http://localhost:3000/login
Content-Type: application/json

{
   "email": "admin@user.com",
   "password": "admin"
}

// em prod deve ser https e não http
###
POST http://localhost:3000/refresh-token
Content-Type: application/json

{
   "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQWRtaW4gVXNlciIsImVtYWlsIjoiYWRtaW5AdXNlci5jb20iLCJpYXQiOjE3NTExMzgyNDksImV4cCI6MTc1MTE3NDI0OSwic3ViIjoiMSJ9.6tUQmWpYurnB-9-DKagC-XKFHyNbRN6f8mmgmDcdLGM"
}


###
GET http://localhost:3000/protected
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQWRtaW4gVXNlciIsImVtYWlsIjoiYWRtaW5AdXNlci5jb20iLCJpYXQiOjE3NTExMzgyNDksImV4cCI6MTc1MTE3NDI0OSwic3ViIjoiMSJ9.6tUQmWpYurnB-9-DKagC-XKFHyNbRN6f8mmgmDcdLGM