POST http://localhost:3000/login
Content-Type: application/json

{
   "email": "admin@user.com",
   "password": "admin"
}

// em prod deve ser https e não http
###
POST http://localhost:3000/refresh-token
Content-Type: application/json

{
   "refresh_token": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQWRtaW4gVXNlciIsImVtYWlsIjoiYWRtaW5AdXNlci5jb20iLCJpYXQiOjE3NTExNDE4MTMsImV4cCI6MTc1MTE3NzgxMywic3ViIjoiMSJ9.EJAwPgGHzFeQCK3DWtEnx5vZIk-yDTqrwc41WieJp5M2xPzZvYyv7p-bZYOPGs8uNi4WOlo0p0rZwhH_FMH0hspvaRgWK4pBMxvY6Kz9NSbaD58pYwHcO2DnL7MLjDfzPoq9pgNsYKVst0Y-qsPzWnYXISwOXj1PFhk7bO_Cq-spsc4d2TGo8Usbw7FYdmPWWQW31ex3zgdzukTQ7-KZr6wCEYYexpWR81se6SgJoT5YMmCxiSQ5R0ODFtHLdfWvI4XvNheRbAdqwznB6z9VGrSjFvxRVV9BovYCnddap9sl6J-41ptUHyMiTewQ8ld0UHJXxCB8icvoaJDZwO7Zgg"
}


###
GET http://localhost:3000/protected
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQWRtaW4gVXNlciIsImVtYWlsIjoiYWRtaW5AdXNlci5jb20iLCJpYXQiOjE3NTExNDE4MjgsImV4cCI6MTc1MTE0MjEyOCwic3ViIjoiMSJ9.OFank_7jE-eubtDmxK9O7s0jPvFUaLNA9V09NECRx5V0i5RvqtZ4vL9EfhPRFLizk9H-G7nt6jz4cS1Mz4ReBu5avjYeiGocl4l_n2g4rPcS0ZYpjs_Q-G839ZjUaXsf0T_VpFgwWMaAHEZEwhijEQeWraArOXWJXxU31guO-g2R-69q_kIG3x-30Z55dnmA1imgoOZ87bybq2PVd6pXz0q0bExYQ6KZ1unE5PgqFmiNcMvECa_s-1E9TxnNuE433UOhS9qsvyoDdy3Dugt-WxjZRuGdk75q1BAFRGYgYxUmZZj_XmIjat_F4wR9NKpeZ1qUpUvlzf40R1ukDEJT_A